import{a as f}from"./assets/vendor-CWxt7QI6.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function c(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=c(t);fetch(t.href,r)}})();const p="https://api.themoviedb.org/3",m="/trending/movie/week",g="345007f9ab440e5b86cef51be6397df1",l=document.querySelector(".js-movie-list"),i=document.querySelector(".js-load-more");i.addEventListener("click",h);let n=1;async function d(e=1){const{data:o}=await f.get(`${p}${m}`,{params:{api_key:g,page:e},headers:{Accept:"application/json",Authorization:"Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIyZjU2NGJhNDBkMTk3OWY0YzFmMzE2NmQzNmFiMTdjNSIsIm5iZiI6MTc2MTQ5MzExMC45MTM5OTk4LCJzdWIiOiI2OGZlNDA3NjI4MjFiZWZkNzZlYWFlY2MiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.vbylhF6rwMOYEqlP0Cl-z6-U5SxCWucPy_OsRQDkPww"}});return o}d(n).then(e=>{console.log(e),l.insertAdjacentHTML("beforeend",u(e.results)),e.page<e.total_pages&&i.classList.replace("load-more-hidden","load-more")}).catch(e=>{alert(e.message)});function u(e){return e.map(({original_title:o,release_date:c,poster_path:s,vote_average:t})=>`
        <li class="movie-card">
            <img src="https://image.tmdb.org/t/p/w300${s}" alt="${o}"/>
            <div class="movie-info">
                <h2>${o}</h2>
                <p>Release Date: ${c}</p>
                <p>Vote Average: ${t}</p>
            </div>
        </li>
    `).join("")}async function h(){n++,i.disabled=!0;try{const e=await d(n);console.log(e),l.insertAdjacentHTML("beforeend",u(e.results)),e.page>=e.total_pages&&i.classList.replace("load-more","load-more-hidden")}catch(e){alert(e.message)}finally{i.disabled=!1}}
//# sourceMappingURL=index.js.map
